/* Flag data for the Wall of Flags interactive map
   Each entry: ISO alpha-3 code → { name, emoji, stripeColor, stripeColorName, flagColors }
   stripeColor = the dominant/most distinctive color from the host flag
   Used to render the Companion Flag preview */

export interface FlagEntry {
  name: string;
  emoji: string;
  stripeColor: string;
  stripeColorName: string;
  flagColors: string[]; // all main colors in the flag for the swatch
  iso2: string;
}

export const flagData: Record<string, FlagEntry> = {
  AFG: { name: "Afghanistan", emoji: "🇦🇫", stripeColor: "#000000", stripeColorName: "Black", flagColors: ["#000000", "#FFFFFF", "#009A44"], iso2: "AF" },
  ALB: { name: "Albania", emoji: "🇦🇱", stripeColor: "#E41E20", stripeColorName: "Red", flagColors: ["#E41E20", "#000000"], iso2: "AL" },
  DZA: { name: "Algeria", emoji: "🇩🇿", stripeColor: "#006233", stripeColorName: "Green", flagColors: ["#006233", "#FFFFFF", "#D21034"], iso2: "DZ" },
  AND: { name: "Andorra", emoji: "🇦🇩", stripeColor: "#003DA5", stripeColorName: "Blue", flagColors: ["#003DA5", "#FEDF00", "#C8102E"], iso2: "AD" },
  AGO: { name: "Angola", emoji: "🇦🇴", stripeColor: "#CC0000", stripeColorName: "Red", flagColors: ["#CC0000", "#000000", "#FFCD00"], iso2: "AO" },
  ARG: { name: "Argentina", emoji: "🇦🇷", stripeColor: "#74ACDF", stripeColorName: "Sky Blue", flagColors: ["#74ACDF", "#FFFFFF", "#F6B40E"], iso2: "AR" },
  ARM: { name: "Armenia", emoji: "🇦🇲", stripeColor: "#D90012", stripeColorName: "Red", flagColors: ["#D90012", "#0033A0", "#F2A800"], iso2: "AM" },
  AUS: { name: "Australia", emoji: "🇦🇺", stripeColor: "#00008B", stripeColorName: "Blue", flagColors: ["#00008B", "#CC0001", "#FFFFFF"], iso2: "AU" },
  AUT: { name: "Austria", emoji: "🇦🇹", stripeColor: "#ED2939", stripeColorName: "Red", flagColors: ["#ED2939", "#FFFFFF"], iso2: "AT" },
  AZE: { name: "Azerbaijan", emoji: "🇦🇿", stripeColor: "#0092BC", stripeColorName: "Blue", flagColors: ["#0092BC", "#E8192C", "#3F9C35"], iso2: "AZ" },
  BHS: { name: "Bahamas", emoji: "🇧🇸", stripeColor: "#00778B", stripeColorName: "Aquamarine", flagColors: ["#00778B", "#FFC72C", "#000000"], iso2: "BS" },
  BHR: { name: "Bahrain", emoji: "🇧🇭", stripeColor: "#CE1126", stripeColorName: "Red", flagColors: ["#CE1126", "#FFFFFF"], iso2: "BH" },
  BGD: { name: "Bangladesh", emoji: "🇧🇩", stripeColor: "#006A4E", stripeColorName: "Green", flagColors: ["#006A4E", "#F42A41"], iso2: "BD" },
  BLR: { name: "Belarus", emoji: "🇧🇾", stripeColor: "#CF101A", stripeColorName: "Red", flagColors: ["#CF101A", "#4AA657", "#FFFFFF"], iso2: "BY" },
  BEL: { name: "Belgium", emoji: "🇧🇪", stripeColor: "#000000", stripeColorName: "Black", flagColors: ["#000000", "#FAE042", "#EF3340"], iso2: "BE" },
  BLZ: { name: "Belize", emoji: "🇧🇿", stripeColor: "#003F87", stripeColorName: "Blue", flagColors: ["#003F87", "#CE1126", "#FFFFFF"], iso2: "BZ" },
  BEN: { name: "Benin", emoji: "🇧🇯", stripeColor: "#008751", stripeColorName: "Green", flagColors: ["#008751", "#FCD116", "#E8112D"], iso2: "BJ" },
  BTN: { name: "Bhutan", emoji: "🇧🇹", stripeColor: "#FF8000", stripeColorName: "Orange", flagColors: ["#FF8000", "#FFFFFF", "#E5252C"], iso2: "BT" },
  BOL: { name: "Bolivia", emoji: "🇧🇴", stripeColor: "#D52B1E", stripeColorName: "Red", flagColors: ["#D52B1E", "#F4E400", "#007A3D"], iso2: "BO" },
  BIH: { name: "Bosnia & Herzegovina", emoji: "🇧🇦", stripeColor: "#002395", stripeColorName: "Blue", flagColors: ["#002395", "#FECB00", "#FFFFFF"], iso2: "BA" },
  BWA: { name: "Botswana", emoji: "🇧🇼", stripeColor: "#75AADB", stripeColorName: "Blue", flagColors: ["#75AADB", "#FFFFFF", "#000000"], iso2: "BW" },
  BRA: { name: "Brazil", emoji: "🇧🇷", stripeColor: "#009C3B", stripeColorName: "Green", flagColors: ["#009C3B", "#FEDF00", "#002776"], iso2: "BR" },
  BRN: { name: "Brunei", emoji: "🇧🇳", stripeColor: "#F7E017", stripeColorName: "Yellow", flagColors: ["#F7E017", "#000000", "#FFFFFF"], iso2: "BN" },
  BGR: { name: "Bulgaria", emoji: "🇧🇬", stripeColor: "#FFFFFF", stripeColorName: "White", flagColors: ["#FFFFFF", "#00966E", "#D62612"], iso2: "BG" },
  BFA: { name: "Burkina Faso", emoji: "🇧🇫", stripeColor: "#EF2B2D", stripeColorName: "Red", flagColors: ["#EF2B2D", "#009A00", "#FCD116"], iso2: "BF" },
  BDI: { name: "Burundi", emoji: "🇧🇮", stripeColor: "#CE1020", stripeColorName: "Red", flagColors: ["#CE1020", "#1EB53A", "#FFFFFF"], iso2: "BI" },
  CPV: { name: "Cabo Verde", emoji: "🇨🇻", stripeColor: "#003893", stripeColorName: "Blue", flagColors: ["#003893", "#CF2027", "#F7D116"], iso2: "CV" },
  KHM: { name: "Cambodia", emoji: "🇰🇭", stripeColor: "#032EA1", stripeColorName: "Blue", flagColors: ["#032EA1", "#E00025", "#FFFFFF"], iso2: "KH" },
  CMR: { name: "Cameroon", emoji: "🇨🇲", stripeColor: "#007A5E", stripeColorName: "Green", flagColors: ["#007A5E", "#CE1126", "#FCD116"], iso2: "CM" },
  CAN: { name: "Canada", emoji: "🇨🇦", stripeColor: "#FF0000", stripeColorName: "Red", flagColors: ["#FF0000", "#FFFFFF"], iso2: "CA" },
  CAF: { name: "Central African Republic", emoji: "🇨🇫", stripeColor: "#003082", stripeColorName: "Blue", flagColors: ["#003082", "#BC0026", "#289728", "#FFCB00"], iso2: "CF" },
  TCD: { name: "Chad", emoji: "🇹🇩", stripeColor: "#002664", stripeColorName: "Blue", flagColors: ["#002664", "#FECB00", "#C60C30"], iso2: "TD" },
  CHL: { name: "Chile", emoji: "🇨🇱", stripeColor: "#D52B1E", stripeColorName: "Red", flagColors: ["#D52B1E", "#FFFFFF", "#003DA5"], iso2: "CL" },
  CHN: { name: "China", emoji: "🇨🇳", stripeColor: "#DE2910", stripeColorName: "Red", flagColors: ["#DE2910", "#FFDE00"], iso2: "CN" },
  COL: { name: "Colombia", emoji: "🇨🇴", stripeColor: "#FCD116", stripeColorName: "Yellow", flagColors: ["#FCD116", "#003087", "#CE1126"], iso2: "CO" },
  COM: { name: "Comoros", emoji: "🇰🇲", stripeColor: "#3A75C4", stripeColorName: "Blue", flagColors: ["#3A75C4", "#3A75C4", "#FFFFFF", "#FFC61E"], iso2: "KM" },
  COD: { name: "Congo (DRC)", emoji: "🇨🇩", stripeColor: "#007FFF", stripeColorName: "Blue", flagColors: ["#007FFF", "#F7D618", "#CE1021"], iso2: "CD" },
  COG: { name: "Congo (Republic)", emoji: "🇨🇬", stripeColor: "#009543", stripeColorName: "Green", flagColors: ["#009543", "#FBDE4A", "#DC241F"], iso2: "CG" },
  CRI: { name: "Costa Rica", emoji: "🇨🇷", stripeColor: "#002B7F", stripeColorName: "Blue", flagColors: ["#002B7F", "#FFFFFF", "#CE1126"], iso2: "CR" },
  CIV: { name: "Côte d'Ivoire", emoji: "🇨🇮", stripeColor: "#F77F00", stripeColorName: "Orange", flagColors: ["#F77F00", "#FFFFFF", "#009A44"], iso2: "CI" },
  HRV: { name: "Croatia", emoji: "🇭🇷", stripeColor: "#FF0000", stripeColorName: "Red", flagColors: ["#FF0000", "#FFFFFF", "#0000FF"], iso2: "HR" },
  CUB: { name: "Cuba", emoji: "🇨🇺", stripeColor: "#002A8F", stripeColorName: "Blue", flagColors: ["#002A8F", "#FFFFFF", "#CC0001"], iso2: "CU" },
  CYP: { name: "Cyprus", emoji: "🇨🇾", stripeColor: "#FFFFFF", stripeColorName: "White", flagColors: ["#FFFFFF", "#D47600", "#4E5B31"], iso2: "CY" },
  CZE: { name: "Czech Republic", emoji: "🇨🇿", stripeColor: "#D7141A", stripeColorName: "Red", flagColors: ["#D7141A", "#FFFFFF", "#11457E"], iso2: "CZ" },
  DNK: { name: "Denmark", emoji: "🇩🇰", stripeColor: "#C60C30", stripeColorName: "Red", flagColors: ["#C60C30", "#FFFFFF"], iso2: "DK" },
  DJI: { name: "Djibouti", emoji: "🇩🇯", stripeColor: "#6AB2E7", stripeColorName: "Light Blue", flagColors: ["#6AB2E7", "#12AD2B", "#FFFFFF", "#D7141A"], iso2: "DJ" },
  DOM: { name: "Dominican Republic", emoji: "🇩🇴", stripeColor: "#002D62", stripeColorName: "Blue", flagColors: ["#002D62", "#FFFFFF", "#CF142B"], iso2: "DO" },
  ECU: { name: "Ecuador", emoji: "🇪🇨", stripeColor: "#FFD100", stripeColorName: "Yellow", flagColors: ["#FFD100", "#034EA2", "#EF3340"], iso2: "EC" },
  EGY: { name: "Egypt", emoji: "🇪🇬", stripeColor: "#CE1126", stripeColorName: "Red", flagColors: ["#CE1126", "#FFFFFF", "#000000", "#C09300"], iso2: "EG" },
  SLV: { name: "El Salvador", emoji: "🇸🇻", stripeColor: "#0F47AF", stripeColorName: "Blue", flagColors: ["#0F47AF", "#FFFFFF"], iso2: "SV" },
  GNQ: { name: "Equatorial Guinea", emoji: "🇬🇶", stripeColor: "#3E9A00", stripeColorName: "Green", flagColors: ["#3E9A00", "#FFFFFF", "#E32118"], iso2: "GQ" },
  ERI: { name: "Eritrea", emoji: "🇪🇷", stripeColor: "#4189DD", stripeColorName: "Blue", flagColors: ["#4189DD", "#4CAA4C", "#D52B1E", "#FCCA3D"], iso2: "ER" },
  EST: { name: "Estonia", emoji: "🇪🇪", stripeColor: "#0072CE", stripeColorName: "Blue", flagColors: ["#0072CE", "#000000", "#FFFFFF"], iso2: "EE" },
  SWZ: { name: "Eswatini", emoji: "🇸🇿", stripeColor: "#3E5EB9", stripeColorName: "Blue", flagColors: ["#3E5EB9", "#FFD900", "#B10C0C"], iso2: "SZ" },
  ETH: { name: "Ethiopia", emoji: "🇪🇹", stripeColor: "#078930", stripeColorName: "Green", flagColors: ["#078930", "#FCDD09", "#DA121A"], iso2: "ET" },
  FJI: { name: "Fiji", emoji: "🇫🇯", stripeColor: "#68BFE5", stripeColorName: "Light Blue", flagColors: ["#68BFE5", "#003F87", "#FFFFFF", "#CF142B"], iso2: "FJ" },
  FIN: { name: "Finland", emoji: "🇫🇮", stripeColor: "#003580", stripeColorName: "Blue", flagColors: ["#003580", "#FFFFFF"], iso2: "FI" },
  FRA: { name: "France", emoji: "🇫🇷", stripeColor: "#002395", stripeColorName: "Blue", flagColors: ["#002395", "#FFFFFF", "#ED2939"], iso2: "FR" },
  GAB: { name: "Gabon", emoji: "🇬🇦", stripeColor: "#009E60", stripeColorName: "Green", flagColors: ["#009E60", "#FCD116", "#003189"], iso2: "GA" },
  GMB: { name: "Gambia", emoji: "🇬🇲", stripeColor: "#3A7728", stripeColorName: "Green", flagColors: ["#3A7728", "#CE1126", "#3A7728", "#FFFFFF", "#0C1C8C"], iso2: "GM" },
  GEO: { name: "Georgia", emoji: "🇬🇪", stripeColor: "#FF0000", stripeColorName: "Red", flagColors: ["#FF0000", "#FFFFFF"], iso2: "GE" },
  DEU: { name: "Germany", emoji: "🇩🇪", stripeColor: "#000000", stripeColorName: "Black", flagColors: ["#000000", "#DD0000", "#FFCE00"], iso2: "DE" },
  GHA: { name: "Ghana", emoji: "🇬🇭", stripeColor: "#006B3F", stripeColorName: "Green", flagColors: ["#006B3F", "#FCD116", "#CE1126", "#000000"], iso2: "GH" },
  GRC: { name: "Greece", emoji: "🇬🇷", stripeColor: "#0D5EAF", stripeColorName: "Blue", flagColors: ["#0D5EAF", "#FFFFFF"], iso2: "GR" },
  GTM: { name: "Guatemala", emoji: "🇬🇹", stripeColor: "#4997D0", stripeColorName: "Blue", flagColors: ["#4997D0", "#FFFFFF"], iso2: "GT" },
  GIN: { name: "Guinea", emoji: "🇬🇳", stripeColor: "#CE1126", stripeColorName: "Red", flagColors: ["#CE1126", "#FCD116", "#009460"], iso2: "GN" },
  GNB: { name: "Guinea-Bissau", emoji: "🇬🇼", stripeColor: "#CE1126", stripeColorName: "Red", flagColors: ["#CE1126", "#FCD116", "#009E49"], iso2: "GW" },
  GUY: { name: "Guyana", emoji: "🇬🇾", stripeColor: "#009E49", stripeColorName: "Green", flagColors: ["#009E49", "#FFFFFF", "#CE1126", "#FCD116", "#000000"], iso2: "GY" },
  HTI: { name: "Haiti", emoji: "🇭🇹", stripeColor: "#00209F", stripeColorName: "Blue", flagColors: ["#00209F", "#D21034"], iso2: "HT" },
  HND: { name: "Honduras", emoji: "🇭🇳", stripeColor: "#0073CF", stripeColorName: "Blue", flagColors: ["#0073CF", "#FFFFFF"], iso2: "HN" },
  HUN: { name: "Hungary", emoji: "🇭🇺", stripeColor: "#CE2939", stripeColorName: "Red", flagColors: ["#CE2939", "#FFFFFF", "#477050"], iso2: "HU" },
  ISL: { name: "Iceland", emoji: "🇮🇸", stripeColor: "#003897", stripeColorName: "Blue", flagColors: ["#003897", "#FFFFFF", "#D72828"], iso2: "IS" },
  IND: { name: "India", emoji: "🇮🇳", stripeColor: "#FF9933", stripeColorName: "Saffron", flagColors: ["#FF9933", "#FFFFFF", "#138808", "#000080"], iso2: "IN" },
  IDN: { name: "Indonesia", emoji: "🇮🇩", stripeColor: "#CE1126", stripeColorName: "Red", flagColors: ["#CE1126", "#FFFFFF"], iso2: "ID" },
  IRN: { name: "Iran", emoji: "🇮🇷", stripeColor: "#239F40", stripeColorName: "Green", flagColors: ["#239F40", "#FFFFFF", "#DA0000"], iso2: "IR" },
  IRQ: { name: "Iraq", emoji: "🇮🇶", stripeColor: "#CE1126", stripeColorName: "Red", flagColors: ["#CE1126", "#FFFFFF", "#000000", "#007A3D"], iso2: "IQ" },
  IRL: { name: "Ireland", emoji: "🇮🇪", stripeColor: "#169B62", stripeColorName: "Green", flagColors: ["#169B62", "#FFFFFF", "#FF883E"], iso2: "IE" },
  ISR: { name: "Israel", emoji: "🇮🇱", stripeColor: "#0038B8", stripeColorName: "Blue", flagColors: ["#0038B8", "#FFFFFF"], iso2: "IL" },
  ITA: { name: "Italy", emoji: "🇮🇹", stripeColor: "#009246", stripeColorName: "Green", flagColors: ["#009246", "#FFFFFF", "#CE2B37"], iso2: "IT" },
  JAM: { name: "Jamaica", emoji: "🇯🇲", stripeColor: "#000000", stripeColorName: "Black", flagColors: ["#000000", "#FED100", "#007749"], iso2: "JM" },
  JPN: { name: "Japan", emoji: "🇯🇵", stripeColor: "#BC002D", stripeColorName: "Crimson", flagColors: ["#BC002D", "#FFFFFF"], iso2: "JP" },
  JOR: { name: "Jordan", emoji: "🇯🇴", stripeColor: "#007A3D", stripeColorName: "Green", flagColors: ["#007A3D", "#FFFFFF", "#000000", "#CE1126"], iso2: "JO" },
  KAZ: { name: "Kazakhstan", emoji: "🇰🇿", stripeColor: "#00AFCA", stripeColorName: "Sky Blue", flagColors: ["#00AFCA", "#FEC50C"], iso2: "KZ" },
  KEN: { name: "Kenya", emoji: "🇰🇪", stripeColor: "#006600", stripeColorName: "Green", flagColors: ["#006600", "#FFFFFF", "#BB0000", "#000000"], iso2: "KE" },
  PRK: { name: "North Korea", emoji: "🇰🇵", stripeColor: "#024FA2", stripeColorName: "Blue", flagColors: ["#024FA2", "#FFFFFF", "#BE0028"], iso2: "KP" },
  KOR: { name: "South Korea", emoji: "🇰🇷", stripeColor: "#FFFFFF", stripeColorName: "White", flagColors: ["#FFFFFF", "#CD2E3A", "#0047A0", "#000000"], iso2: "KR" },
  KWT: { name: "Kuwait", emoji: "🇰🇼", stripeColor: "#007A3D", stripeColorName: "Green", flagColors: ["#007A3D", "#FFFFFF", "#CE1126", "#000000"], iso2: "KW" },
  KGZ: { name: "Kyrgyzstan", emoji: "🇰🇬", stripeColor: "#E8112D", stripeColorName: "Red", flagColors: ["#E8112D", "#FFCD00"], iso2: "KG" },
  LAO: { name: "Laos", emoji: "🇱🇦", stripeColor: "#CE1126", stripeColorName: "Red", flagColors: ["#CE1126", "#002868", "#FFFFFF"], iso2: "LA" },
  LVA: { name: "Latvia", emoji: "🇱🇻", stripeColor: "#9E3039", stripeColorName: "Carmine", flagColors: ["#9E3039", "#FFFFFF"], iso2: "LV" },
  LBN: { name: "Lebanon", emoji: "🇱🇧", stripeColor: "#FFFFFF", stripeColorName: "White", flagColors: ["#FFFFFF", "#EE161F", "#00A651"], iso2: "LB" },
  LSO: { name: "Lesotho", emoji: "🇱🇸", stripeColor: "#009A44", stripeColorName: "Green", flagColors: ["#009A44", "#FFFFFF", "#009A44", "#000000"], iso2: "LS" },
  LBR: { name: "Liberia", emoji: "🇱🇷", stripeColor: "#BF0A30", stripeColorName: "Red", flagColors: ["#BF0A30", "#FFFFFF", "#002868"], iso2: "LR" },
  LBY: { name: "Libya", emoji: "🇱🇾", stripeColor: "#000000", stripeColorName: "Black", flagColors: ["#000000", "#FFFFFF", "#239E46"], iso2: "LY" },
  LIE: { name: "Liechtenstein", emoji: "🇱🇮", stripeColor: "#002B7F", stripeColorName: "Blue", flagColors: ["#002B7F", "#CE1126", "#FFD83D"], iso2: "LI" },
  LTU: { name: "Lithuania", emoji: "🇱🇹", stripeColor: "#FDB913", stripeColorName: "Yellow", flagColors: ["#FDB913", "#006A44", "#C1272D"], iso2: "LT" },
  LUX: { name: "Luxembourg", emoji: "🇱🇺", stripeColor: "#EF3340", stripeColorName: "Red", flagColors: ["#EF3340", "#FFFFFF", "#00A3E0"], iso2: "LU" },
  MDG: { name: "Madagascar", emoji: "🇲🇬", stripeColor: "#FC3D32", stripeColorName: "Red", flagColors: ["#FC3D32", "#FFFFFF", "#007E3A"], iso2: "MG" },
  MWI: { name: "Malawi", emoji: "🇲🇼", stripeColor: "#000000", stripeColorName: "Black", flagColors: ["#000000", "#CE1126", "#339E35"], iso2: "MW" },
  MYS: { name: "Malaysia", emoji: "🇲🇾", stripeColor: "#CC0001", stripeColorName: "Red", flagColors: ["#CC0001", "#FFFFFF", "#003087", "#FFD100"], iso2: "MY" },
  MDV: { name: "Maldives", emoji: "🇲🇻", stripeColor: "#D21034", stripeColorName: "Red", flagColors: ["#D21034", "#007E3A", "#FFFFFF"], iso2: "MV" },
  MLI: { name: "Mali", emoji: "🇲🇱", stripeColor: "#009A00", stripeColorName: "Green", flagColors: ["#009A00", "#FCD116", "#CE1126"], iso2: "ML" },
  MLT: { name: "Malta", emoji: "🇲🇹", stripeColor: "#CF142B", stripeColorName: "Red", flagColors: ["#CF142B", "#FFFFFF"], iso2: "MT" },
  MRT: { name: "Mauritania", emoji: "🇲🇷", stripeColor: "#006233", stripeColorName: "Green", flagColors: ["#006233", "#FFD700", "#D01C1F"], iso2: "MR" },
  MUS: { name: "Mauritius", emoji: "🇲🇺", stripeColor: "#EA2839", stripeColorName: "Red", flagColors: ["#EA2839", "#1A206D", "#FFD500", "#00A551"], iso2: "MU" },
  MEX: { name: "Mexico", emoji: "🇲🇽", stripeColor: "#006847", stripeColorName: "Green", flagColors: ["#006847", "#FFFFFF", "#CE1126"], iso2: "MX" },
  MDA: { name: "Moldova", emoji: "🇲🇩", stripeColor: "#003DA5", stripeColorName: "Blue", flagColors: ["#003DA5", "#FFD200", "#CC0000"], iso2: "MD" },
  MCO: { name: "Monaco", emoji: "🇲🇨", stripeColor: "#CE1126", stripeColorName: "Red", flagColors: ["#CE1126", "#FFFFFF"], iso2: "MC" },
  MNG: { name: "Mongolia", emoji: "🇲🇳", stripeColor: "#C4272F", stripeColorName: "Red", flagColors: ["#C4272F", "#015197", "#F9CF02"], iso2: "MN" },
  MNE: { name: "Montenegro", emoji: "🇲🇪", stripeColor: "#D4AF37", stripeColorName: "Gold", flagColors: ["#D4AF37", "#D4AF37", "#D62828"], iso2: "ME" },
  MAR: { name: "Morocco", emoji: "🇲🇦", stripeColor: "#C1272D", stripeColorName: "Red", flagColors: ["#C1272D", "#006233"], iso2: "MA" },
  MOZ: { name: "Mozambique", emoji: "🇲🇿", stripeColor: "#009A44", stripeColorName: "Green", flagColors: ["#009A44", "#FFFFFF", "#FCE100", "#000000", "#D21034"], iso2: "MZ" },
  MMR: { name: "Myanmar", emoji: "🇲🇲", stripeColor: "#FECB00", stripeColorName: "Yellow", flagColors: ["#FECB00", "#34B233", "#EA2839", "#FFFFFF"], iso2: "MM" },
  NAM: { name: "Namibia", emoji: "🇳🇦", stripeColor: "#003580", stripeColorName: "Blue", flagColors: ["#003580", "#FFFFFF", "#D21034", "#009A44"], iso2: "NA" },
  NPL: { name: "Nepal", emoji: "🇳🇵", stripeColor: "#003893", stripeColorName: "Blue", flagColors: ["#003893", "#FFFFFF", "#DC143C"], iso2: "NP" },
  NLD: { name: "Netherlands", emoji: "🇳🇱", stripeColor: "#AE1C28", stripeColorName: "Red", flagColors: ["#AE1C28", "#FFFFFF", "#21468B"], iso2: "NL" },
  NZL: { name: "New Zealand", emoji: "🇳🇿", stripeColor: "#00247D", stripeColorName: "Blue", flagColors: ["#00247D", "#CC142B", "#FFFFFF"], iso2: "NZ" },
  NIC: { name: "Nicaragua", emoji: "🇳🇮", stripeColor: "#3D6CB9", stripeColorName: "Blue", flagColors: ["#3D6CB9", "#FFFFFF"], iso2: "NI" },
  NER: { name: "Niger", emoji: "🇳🇪", stripeColor: "#E05206", stripeColorName: "Orange", flagColors: ["#E05206", "#FFFFFF", "#009A00"], iso2: "NE" },
  NGA: { name: "Nigeria", emoji: "🇳🇬", stripeColor: "#008751", stripeColorName: "Green", flagColors: ["#008751", "#FFFFFF"], iso2: "NG" },
  MKD: { name: "North Macedonia", emoji: "🇲🇰", stripeColor: "#CE2028", stripeColorName: "Red", flagColors: ["#CE2028", "#F7D618"], iso2: "MK" },
  NOR: { name: "Norway", emoji: "🇳🇴", stripeColor: "#EF2B2D", stripeColorName: "Red", flagColors: ["#EF2B2D", "#FFFFFF", "#002868"], iso2: "NO" },
  OMN: { name: "Oman", emoji: "🇴🇲", stripeColor: "#DB161B", stripeColorName: "Red", flagColors: ["#DB161B", "#FFFFFF", "#008000"], iso2: "OM" },
  PAK: { name: "Pakistan", emoji: "🇵🇰", stripeColor: "#01411C", stripeColorName: "Green", flagColors: ["#01411C", "#FFFFFF"], iso2: "PK" },
  PLW: { name: "Palau", emoji: "🇵🇼", stripeColor: "#4AADD6", stripeColorName: "Blue", flagColors: ["#4AADD6", "#FFDE00"], iso2: "PW" },
  PAN: { name: "Panama", emoji: "🇵🇦", stripeColor: "#FFFFFF", stripeColorName: "White", flagColors: ["#FFFFFF", "#DA121A", "#1C3F94"], iso2: "PA" },
  PNG: { name: "Papua New Guinea", emoji: "🇵🇬", stripeColor: "#000000", stripeColorName: "Black", flagColors: ["#000000", "#CE1126", "#FCD116"], iso2: "PG" },
  PRY: { name: "Paraguay", emoji: "🇵🇾", stripeColor: "#D52B1E", stripeColorName: "Red", flagColors: ["#D52B1E", "#FFFFFF", "#0038A8"], iso2: "PY" },
  PER: { name: "Peru", emoji: "🇵🇪", stripeColor: "#D91023", stripeColorName: "Red", flagColors: ["#D91023", "#FFFFFF"], iso2: "PE" },
  PHL: { name: "Philippines", emoji: "🇵🇭", stripeColor: "#0038A8", stripeColorName: "Blue", flagColors: ["#0038A8", "#CE1126", "#FFFFFF", "#FCD116"], iso2: "PH" },
  POL: { name: "Poland", emoji: "🇵🇱", stripeColor: "#DC143C", stripeColorName: "Crimson", flagColors: ["#FFFFFF", "#DC143C"], iso2: "PL" },
  PRT: { name: "Portugal", emoji: "🇵🇹", stripeColor: "#006600", stripeColorName: "Green", flagColors: ["#006600", "#FF0000", "#FFD700"], iso2: "PT" },
  QAT: { name: "Qatar", emoji: "🇶🇦", stripeColor: "#8D1B3D", stripeColorName: "Maroon", flagColors: ["#8D1B3D", "#FFFFFF"], iso2: "QA" },
  ROU: { name: "Romania", emoji: "🇷🇴", stripeColor: "#002B7F", stripeColorName: "Blue", flagColors: ["#002B7F", "#FCD116", "#CE1126"], iso2: "RO" },
  RUS: { name: "Russia", emoji: "🇷🇺", stripeColor: "#FFFFFF", stripeColorName: "White", flagColors: ["#FFFFFF", "#0039A6", "#D52B1E"], iso2: "RU" },
  RWA: { name: "Rwanda", emoji: "🇷🇼", stripeColor: "#20603D", stripeColorName: "Green", flagColors: ["#20603D", "#FAD201", "#00A1DE"], iso2: "RW" },
  SAU: { name: "Saudi Arabia", emoji: "🇸🇦", stripeColor: "#006C35", stripeColorName: "Green", flagColors: ["#006C35", "#FFFFFF"], iso2: "SA" },
  SEN: { name: "Senegal", emoji: "🇸🇳", stripeColor: "#00853F", stripeColorName: "Green", flagColors: ["#00853F", "#FDEF42", "#E31B23"], iso2: "SN" },
  SRB: { name: "Serbia", emoji: "🇷🇸", stripeColor: "#C6363C", stripeColorName: "Red", flagColors: ["#C6363C", "#0C4076", "#FFFFFF"], iso2: "RS" },
  SLE: { name: "Sierra Leone", emoji: "🇸🇱", stripeColor: "#1EB53A", stripeColorName: "Green", flagColors: ["#1EB53A", "#FFFFFF", "#0072C6"], iso2: "SL" },
  SGP: { name: "Singapore", emoji: "🇸🇬", stripeColor: "#EF3340", stripeColorName: "Red", flagColors: ["#EF3340", "#FFFFFF"], iso2: "SG" },
  SVK: { name: "Slovakia", emoji: "🇸🇰", stripeColor: "#FFFFFF", stripeColorName: "White", flagColors: ["#FFFFFF", "#0B4EA2", "#EE1C25"], iso2: "SK" },
  SVN: { name: "Slovenia", emoji: "🇸🇮", stripeColor: "#003DA5", stripeColorName: "Blue", flagColors: ["#003DA5", "#FFFFFF", "#ED2939"], iso2: "SI" },
  SOM: { name: "Somalia", emoji: "🇸🇴", stripeColor: "#4189DD", stripeColorName: "Blue", flagColors: ["#4189DD", "#FFFFFF"], iso2: "SO" },
  ZAF: { name: "South Africa", emoji: "🇿🇦", stripeColor: "#007A4D", stripeColorName: "Green", flagColors: ["#007A4D", "#FFB81C", "#DE3831", "#002395", "#FFFFFF", "#000000"], iso2: "ZA" },
  SSD: { name: "South Sudan", emoji: "🇸🇸", stripeColor: "#078930", stripeColorName: "Green", flagColors: ["#078930", "#FFFFFF", "#DA121A", "#000000", "#FCDD09"], iso2: "SS" },
  ESP: { name: "Spain", emoji: "🇪🇸", stripeColor: "#AA151B", stripeColorName: "Red", flagColors: ["#AA151B", "#F1BF00"], iso2: "ES" },
  LKA: { name: "Sri Lanka", emoji: "🇱🇰", stripeColor: "#8D153A", stripeColorName: "Maroon", flagColors: ["#8D153A", "#F47B20", "#006B3F", "#FFD100"], iso2: "LK" },
  SDN: { name: "Sudan", emoji: "🇸🇩", stripeColor: "#D21034", stripeColorName: "Red", flagColors: ["#D21034", "#FFFFFF", "#000000", "#007229"], iso2: "SD" },
  SUR: { name: "Suriname", emoji: "🇸🇷", stripeColor: "#377E3F", stripeColorName: "Green", flagColors: ["#377E3F", "#FFFFFF", "#B40A2D", "#ECC81D"], iso2: "SR" },
  SWE: { name: "Sweden", emoji: "🇸🇪", stripeColor: "#006AA7", stripeColorName: "Blue", flagColors: ["#006AA7", "#FECC02"], iso2: "SE" },
  CHE: { name: "Switzerland", emoji: "🇨🇭", stripeColor: "#FF0000", stripeColorName: "Red", flagColors: ["#FF0000", "#FFFFFF"], iso2: "CH" },
  SYR: { name: "Syria", emoji: "🇸🇾", stripeColor: "#CE1126", stripeColorName: "Red", flagColors: ["#CE1126", "#000000", "#FFFFFF", "#007A3D"], iso2: "SY" },
  TWN: { name: "Taiwan", emoji: "🇹🇼", stripeColor: "#FE0000", stripeColorName: "Red", flagColors: ["#FE0000", "#FFFFFF", "#000095"], iso2: "TW" },
  TJK: { name: "Tajikistan", emoji: "🇹🇯", stripeColor: "#CC0000", stripeColorName: "Red", flagColors: ["#CC0000", "#FFFFFF", "#006600", "#F8C300"], iso2: "TJ" },
  TZA: { name: "Tanzania", emoji: "🇹🇿", stripeColor: "#1EB53A", stripeColorName: "Green", flagColors: ["#1EB53A", "#FCD116", "#000000", "#00A3DD"], iso2: "TZ" },
  THA: { name: "Thailand", emoji: "🇹🇭", stripeColor: "#A51931", stripeColorName: "Red", flagColors: ["#A51931", "#FFFFFF", "#2D2A4A"], iso2: "TH" },
  TLS: { name: "Timor-Leste", emoji: "🇹🇱", stripeColor: "#DC241F", stripeColorName: "Red", flagColors: ["#DC241F", "#FDC82F", "#000000", "#FFFFFF"], iso2: "TL" },
  TGO: { name: "Togo", emoji: "🇹🇬", stripeColor: "#006A4E", stripeColorName: "Green", flagColors: ["#006A4E", "#FFCE00", "#D21034", "#FFFFFF"], iso2: "TG" },
  TTO: { name: "Trinidad & Tobago", emoji: "🇹🇹", stripeColor: "#CE1126", stripeColorName: "Red", flagColors: ["#CE1126", "#000000", "#FFFFFF"], iso2: "TT" },
  TUN: { name: "Tunisia", emoji: "🇹🇳", stripeColor: "#E70013", stripeColorName: "Red", flagColors: ["#E70013", "#FFFFFF"], iso2: "TN" },
  TUR: { name: "Turkey", emoji: "🇹🇷", stripeColor: "#E30A17", stripeColorName: "Red", flagColors: ["#E30A17", "#FFFFFF"], iso2: "TR" },
  TKM: { name: "Turkmenistan", emoji: "🇹🇲", stripeColor: "#1CAA53", stripeColorName: "Green", flagColors: ["#1CAA53", "#CC0000", "#FFFFFF"], iso2: "TM" },
  UGA: { name: "Uganda", emoji: "🇺🇬", stripeColor: "#000000", stripeColorName: "Black", flagColors: ["#000000", "#FCDC04", "#D90000", "#FFFFFF"], iso2: "UG" },
  UKR: { name: "Ukraine", emoji: "🇺🇦", stripeColor: "#005BBB", stripeColorName: "Blue", flagColors: ["#005BBB", "#FFD500"], iso2: "UA" },
  ARE: { name: "United Arab Emirates", emoji: "🇦🇪", stripeColor: "#00732F", stripeColorName: "Green", flagColors: ["#00732F", "#FFFFFF", "#000000", "#FF0000"], iso2: "AE" },
  GBR: { name: "United Kingdom", emoji: "🇬🇧", stripeColor: "#012169", stripeColorName: "Blue", flagColors: ["#012169", "#FFFFFF", "#C8102E"], iso2: "GB" },
  USA: { name: "United States", emoji: "🇺🇸", stripeColor: "#B22234", stripeColorName: "Red", flagColors: ["#B22234", "#FFFFFF", "#3C3B6E"], iso2: "US" },
  URY: { name: "Uruguay", emoji: "🇺🇾", stripeColor: "#FFFFFF", stripeColorName: "White", flagColors: ["#FFFFFF", "#0038A8", "#FCD116"], iso2: "UY" },
  UZB: { name: "Uzbekistan", emoji: "🇺🇿", stripeColor: "#1EB53A", stripeColorName: "Green", flagColors: ["#1EB53A", "#FFFFFF", "#CE1126", "#009FCA"], iso2: "UZ" },
  VEN: { name: "Venezuela", emoji: "🇻🇪", stripeColor: "#CF142B", stripeColorName: "Red", flagColors: ["#CF142B", "#FFD100", "#003087"], iso2: "VE" },
  VNM: { name: "Vietnam", emoji: "🇻🇳", stripeColor: "#DA251D", stripeColorName: "Red", flagColors: ["#DA251D", "#FFCD00"], iso2: "VN" },
  YEM: { name: "Yemen", emoji: "🇾🇪", stripeColor: "#CE1126", stripeColorName: "Red", flagColors: ["#CE1126", "#FFFFFF", "#000000"], iso2: "YE" },
  ZMB: { name: "Zambia", emoji: "🇿🇲", stripeColor: "#198A00", stripeColorName: "Green", flagColors: ["#198A00", "#EF7D00", "#000000", "#DE2010"], iso2: "ZM" },
  ZWE: { name: "Zimbabwe", emoji: "🇿🇼", stripeColor: "#006400", stripeColorName: "Green", flagColors: ["#006400", "#FFD200", "#D21034", "#000000", "#FFFFFF"], iso2: "ZW" },
};

export const searchFlags = (query: string): Array<{ code: string; entry: FlagEntry }> => {
  const q = query.toLowerCase().trim();
  if (!q) return [];
  return Object.entries(flagData)
    .filter(([, entry]) => entry.name.toLowerCase().includes(q))
    .map(([code, entry]) => ({ code, entry }))
    .slice(0, 8);
};
